---
ID: "f0ead83d-a231-420a-8c53-bf66b0726b2c"
Parent: "0b8a5ed2-fb6c-412f-a64b-cbeac7e3c3af"
Template: "0b8a5ed2-fb6c-412f-a64b-cbeac7e3c3af"
Path: /sitecore/templates/Project/PLAY/OHA/Blog/Blog/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "27e8a9ee-e5ff-499a-a4f1-bcaf566ed261"
