---
ID: "74dfd13c-852b-4914-a65f-d5f3d0bc6cfd"
Parent: "15b20460-d0d7-4014-a63d-cee29d88e146"
Template: "6db09cef-64a8-52a3-a980-38408109c4d7"
Path: /sitecore/content/PLAY/playwebsite/XMCDemoHome/productcategory
SharedFields:
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{B73A117A-11C2-4B86-8A5C-4C7648EE87DE}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{8F0E1432-3729-462B-AD20-DAF067694BCB}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{C8B08363-3DE3-4AB9-B53A-556228BD98E7}" />
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{5ED0A33A-5A27-4EA6-A3D8-C1C3959246D8}"
          s:ds=""
          s:id="{2F9D05FD-8E58-56CC-B586-41A3EC155CD7}"
          s:par=""
          s:ph="/headless-main"
          s:ccb="Clear on publish" />
      </d>
    </r>
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{4692FE56-0DE5-467D-9ED2-CF11494701BA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{5ED0A33A-5A27-4EA6-A3D8-C1C3959246D8}">
              <p:d />
            </r>
            <r
              uid="{A778DA15-EFA7-43EF-B52D-A6FB91C2B3F8}"
              p:before="*"
              s:ds="{AF8CC5C3-3121-4DBF-8C59-3AC009E6B3C8}"
              s:id="{60E46443-0BAD-5861-823D-75F620401573}"
              s:par="FieldNames&amp;CacheClearingBehavior=Clear+on+publish&amp;Styles&amp;CSSStyles&amp;GridParameters&amp;BannerType=BannerWithoutCTA"
              s:ph="headless-main"
              s:ccb="Clear on publish" />
            <r
              uid="{3E86CBD8-4A97-4F0F-85F8-37EBC7B3FDE7}"
              p:after="r[@uid='{A778DA15-EFA7-43EF-B52D-A6FB91C2B3F8}']"
              s:ds=""
              s:id="{2F9D05FD-8E58-56CC-B586-41A3EC155CD7}"
              s:par="FieldNames&amp;CacheClearingBehavior=Clear+on+publish&amp;RenderingIdentifier&amp;Styles&amp;CSSStyles"
              s:ph="headless-main"
              s:ccb="Clear on publish" />
            <r
              uid="{BFBC7DA7-D414-4BAB-BF76-D8BE36F51F75}"
              p:after="r[@uid='{3E86CBD8-4A97-4F0F-85F8-37EBC7B3FDE7}']"
              s:ds="{836DF427-37F5-4C30-8E28-C9A34D18A215}"
              s:id="{EA63DC31-3AE7-4FE1-B248-2A230EDAF806}"
              s:par="CacheClearingBehavior=Clear+on+publish&amp;CSSStyles"
              s:ph="headless-main"
              s:ccb="Clear on publish" />
            <r
              uid="{8C215CF6-DC3F-4412-A633-4796F73321BA}"
              p:after="r[@uid='{BFBC7DA7-D414-4BAB-BF76-D8BE36F51F75}']"
              s:ds="{7421BC99-2E33-4365-99E9-D0A87922C0C7}"
              s:id="{1C1FC053-EC78-4B8F-AB05-6CEF601D9B2B}"
              s:par="CacheClearingBehavior=Clear+on+publish&amp;CSSStyles"
              s:ph="headless-main"
              s:ccb="Clear on publish" />
            <r
              uid="{F04D0CB3-9BA6-4A86-9A5F-10E4B2F8B2AA}"
              p:after="*[1=2]"
              s:ds="{F14EA3FD-9973-49A4-9F3D-A3B92F7A6B5F}"
              s:id="{9D08882D-839D-40C2-817F-C51A6E51F769}"
              s:par="FieldNames&amp;CacheClearingBehavior=Clear+on+publish&amp;Styles&amp;CSSStyles&amp;GridParameters&amp;ListingType=Ellipse"
              s:ph="headless-main"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{836E0687-CDFF-4087-9E3B-C8ECAFE11746}"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "67354ef2-594c-44f4-96f6-e523139a2304"
    - ID: "ed69eacf-5eb2-5050-9d5b-997812318dde"
      Hint: pageTitle
      Value: Product Page
