---
ID: "c9af4ca2-2f37-4f78-9ca2-2afed90274b3"
Parent: "6c3614a6-2e6e-4bbd-b84f-2568d221a909"
Template: "687f1da8-c510-48bd-bc13-af46b616337a"
Path: /sitecore/content/PLAY/playwebsite/Data/OHA/Header 3 step Navigation Data/HeaderNavigationFolder/MainNavigation/Product Category
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "db8598a9-5383-4c01-9375-2caa43152e3a"
    - ID: "bcdbf166-d7a5-4a34-8e6e-0bd04a79444f"
      Hint: Link
      Value: |
        <link class="" id="{74DFD13C-852B-4914-A65F-D5F3D0BC6CFD}" querystring="" anchor="" target="" title="" linktype="internal" text="Product Category" url="/PLAY/playwebsite/sxastarter/productcategory" />
