---
ID: "0e8cfd79-acfc-4cd7-b846-5a15a1443dd8"
Parent: "f300aaaf-78b9-463e-9e23-88d5d27cc170"
Template: "24cfc9db-f9a7-4238-9041-d29c0f927f75"
Path: /sitecore/content/PLAY/playwebsite/home/OHAHomepage/Page Components/product
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "58900afa-09c0-4718-9c99-e9c965f6c78e"
