---
ID: "486a1a5b-e15d-5976-bbfc-e65d3f019a80"
Parent: "31597eb0-a844-5546-9f7f-0b0dc067dc34"
Template: "31597eb0-a844-5546-9f7f-0b0dc067dc34"
Path: /sitecore/templates/Project/PLAY/OHA/Search/SearchBar Rendering Parameters/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "15ac5d16-5f08-4570-b4d4-134f07a6a3ce"
