---
ID: "a211ba50-8ae6-45d1-85a3-6d8ed4313456"
Parent: "2fb5abc5-d536-4691-8e11-f7832a8ef50d"
Template: "ec25ce9d-75a3-491e-ba82-347de22176f9"
Path: /sitecore/content/PLAY/playwebsite/XMCDemoHome/productcategory/Page Components/Category Group/CategoryItems/Training Shirt
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1800
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "59392481-7824-4649-982c-26c6fee508f1"
    - ID: "e5badbad-aa22-4ae3-8212-601ae7d94ac9"
      Hint: itemName
      Value: Training Shirt
