---
ID: "a211ba50-8ae6-45d1-85a3-6d8ed4313456"
Parent: "2fb5abc5-d536-4691-8e11-f7832a8ef50d"
Template: "ec25ce9d-75a3-491e-ba82-347de22176f9"
Path: /sitecore/content/PLAY/playwebsite/XMCDemoHome/productcategory/Page Components/Category Group/CategoryItems/Training Shirt
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fbf73725-c46d-458f-b375-a475f34c4824"
    - ID: "e5badbad-aa22-4ae3-8212-601ae7d94ac9"
      Hint: itemName
      Value: Training Shirt
