---
ID: "c2a1b388-6e57-4321-9168-1a499f76d26b"
Parent: "503b4548-cf6c-4221-903d-573ea3dcfa0b"
Template: "503b4548-cf6c-4221-903d-573ea3dcfa0b"
Path: /sitecore/templates/Project/XMCloudSite/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230619T104517Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\asmita.parkar@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\asmita.parkar@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a947aab9-3fc5-40dd-b142-b766c566f8be"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asmita.parkar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230619T104517Z
