---
ID: "f4b4f2c3-f341-4cae-9fca-a233e6f44f19"
Parent: "3fa258c6-f221-466a-8e81-d26372500cd2"
Template: "3fa258c6-f221-466a-8e81-d26372500cd2"
Path: /sitecore/templates/Project/PLAY/OHA/ProductCategory/ProductCategory Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "02d2a1f1-5846-4e62-aec1-3c9ec15f52d4"
